import { Conversation, Message } from '@/types';

export const mockMessages: Message[] = [
    {
        id: 'msg-001',
        conversationId: 'conv-001',
        senderId: 'staff-001',
        senderName: 'Adebayo Johnson',
        content: 'Hi Chioma, did you review the lecture notes I shared?',
        sentAt: new Date(Date.now() - 3600000).toISOString(),
        isEdited: false,
    },
    {
        id: 'msg-002',
        conversationId: 'conv-001',
        senderId: 'staff-002',
        senderName: 'Chioma Okafor',
        content: 'Yes, I did! They are very comprehensive. Great work.',
        sentAt: new Date(Date.now() - 3300000).toISOString(),
        isEdited: false,
    },
    {
        id: 'msg-003',
        conversationId: 'conv-001',
        senderId: 'staff-001',
        senderName: 'Adebayo Johnson',
        content: 'I have some additional materials for the upcoming seminar',
        sentAt: new Date(Date.now() - 2700000).toISOString(),
        isEdited: false,
    },
    {
        id: 'msg-004',
        conversationId: 'conv-001',
        senderId: 'staff-001',
        senderName: 'Adebayo Johnson',
        content: 'Sending the PDF now',
        media: [
            {
                id: 'media-001',
                type: 'document',
                url: 'https://example.com/seminar-notes.pdf',
                name: 'seminar-notes.pdf',
                size: 2048576,
                mimeType: 'application/pdf',
            },
        ],
        sentAt: new Date(Date.now() - 2400000).toISOString(),
        isEdited: false,
    },
    {
        id: 'msg-005',
        conversationId: 'conv-001',
        senderId: 'staff-002',
        senderName: 'Chioma Okafor',
        content: 'Perfect! Thank you for sharing. I will review and get back to you.',
        sentAt: new Date(Date.now() - 1800000).toISOString(),
        readAt: new Date(Date.now() - 1200000).toISOString(),
        isEdited: false,
    },
    {
        id: 'msg-006',
        conversationId: 'conv-002',
        senderId: 'staff-003',
        senderName: 'Emeka Nwankwo',
        content: 'The project proposal looks good. Can we meet tomorrow?',
        sentAt: new Date(Date.now() - 5400000).toISOString(),
        isEdited: false,
    },
    {
        id: 'msg-007',
        conversationId: 'conv-002',
        senderId: 'staff-001',
        senderName: 'Adebayo Johnson',
        content: 'Sure! Tomorrow at 2 PM works for me.',
        sentAt: new Date(Date.now() - 5100000).toISOString(),
        isEdited: false,
    },
    {
        id: 'msg-008',
        conversationId: 'conv-003',
        senderId: 'staff-002',
        senderName: 'Chioma Okafor',
        content: 'Here are the updated exam results as requested',
        media: [
            {
                id: 'media-002',
                type: 'document',
                url: 'https://example.com/exam-results.xlsx',
                name: 'exam-results.xlsx',
                size: 512000,
                mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            },
        ],
        sentAt: new Date(Date.now() - 7200000).toISOString(),
        isEdited: false,
    },
    {
        id: 'msg-009',
        conversationId: 'conv-003',
        senderId: 'staff-003',
        senderName: 'Emeka Nwankwo',
        content: 'Thank you! This is exactly what I needed.',
        sentAt: new Date(Date.now() - 6900000).toISOString(),
        readAt: new Date(Date.now() - 6600000).toISOString(),
        isEdited: false,
    },
];

export const mockConversations: Conversation[] = [
    {
        id: 'conv-001',
        participantIds: ['staff-001', 'staff-002'],
        participants: [
            {
                id: 'staff-001',
                email: 'adebayo.johnson@unilag.edu.ng',
                firstName: 'Adebayo',
                lastName: 'Johnson',
                department: 'Computer Science',
                institution: 'University of Lagos',
                role: 'staff',
                createdAt: '2024-01-15T09:00:00Z',
                lastLogin: '2025-01-14T14:30:00Z',
            },
            {
                id: 'staff-002',
                email: 'chioma.okafor@unilag.edu.ng',
                firstName: 'Chioma',
                lastName: 'Okafor',
                department: 'Mathematics',
                institution: 'University of Lagos',
                role: 'staff',
                createdAt: '2024-02-20T10:00:00Z',
                lastLogin: '2025-01-14T09:15:00Z',
            },
        ],
        lastMessage: {
            id: 'msg-005',
            conversationId: 'conv-001',
            senderId: 'staff-002',
            senderName: 'Chioma Okafor',
            content: 'Perfect! Thank you for sharing. I will review and get back to you.',
            sentAt: new Date(Date.now() - 1800000).toISOString(),
            readAt: new Date(Date.now() - 1200000).toISOString(),
            isEdited: false,
        },
        unreadCount: 0,
        createdAt: '2025-01-10T08:00:00Z',
        updatedAt: new Date(Date.now() - 1800000).toISOString(),
        isArchived: false,
    },
    {
        id: 'conv-002',
        participantIds: ['staff-001', 'staff-003'],
        participants: [
            {
                id: 'staff-001',
                email: 'adebayo.johnson@unilag.edu.ng',
                firstName: 'Adebayo',
                lastName: 'Johnson',
                department: 'Computer Science',
                institution: 'University of Lagos',
                role: 'staff',
                createdAt: '2024-01-15T09:00:00Z',
                lastLogin: '2025-01-14T14:30:00Z',
            },
            {
                id: 'staff-003',
                email: 'emeka.nwankwo@oauife.edu.ng',
                firstName: 'Emeka',
                lastName: 'Nwankwo',
                department: 'Engineering',
                institution: 'Obafemi Awolowo University',
                role: 'staff',
                createdAt: '2024-03-10T08:00:00Z',
                lastLogin: '2025-01-13T16:45:00Z',
            },
        ],
        lastMessage: {
            id: 'msg-007',
            conversationId: 'conv-002',
            senderId: 'staff-001',
            senderName: 'Adebayo Johnson',
            content: 'Sure! Tomorrow at 2 PM works for me.',
            sentAt: new Date(Date.now() - 5100000).toISOString(),
            isEdited: false,
        },
        unreadCount: 1,
        createdAt: '2025-01-08T10:30:00Z',
        updatedAt: new Date(Date.now() - 5100000).toISOString(),
        isArchived: false,
    },
    {
        id: 'conv-003',
        participantIds: ['staff-002', 'staff-003'],
        participants: [
            {
                id: 'staff-002',
                email: 'chioma.okafor@unilag.edu.ng',
                firstName: 'Chioma',
                lastName: 'Okafor',
                department: 'Mathematics',
                institution: 'University of Lagos',
                role: 'staff',
                createdAt: '2024-02-20T10:00:00Z',
                lastLogin: '2025-01-14T09:15:00Z',
            },
            {
                id: 'staff-003',
                email: 'emeka.nwankwo@oauife.edu.ng',
                firstName: 'Emeka',
                lastName: 'Nwankwo',
                department: 'Engineering',
                institution: 'Obafemi Awolowo University',
                role: 'staff',
                createdAt: '2024-03-10T08:00:00Z',
                lastLogin: '2025-01-13T16:45:00Z',
            },
        ],
        lastMessage: {
            id: 'msg-009',
            conversationId: 'conv-003',
            senderId: 'staff-003',
            senderName: 'Emeka Nwankwo',
            content: 'Thank you! This is exactly what I needed.',
            sentAt: new Date(Date.now() - 6900000).toISOString(),
            readAt: new Date(Date.now() - 6600000).toISOString(),
            isEdited: false,
        },
        unreadCount: 0,
        createdAt: '2025-01-05T14:00:00Z',
        updatedAt: new Date(Date.now() - 6900000).toISOString(),
        isArchived: false,
    },
];
