import { SharedFile, FileActivity } from '@/types';

export const mockFiles: SharedFile[] = [
  {
    id: 'file-001',
    name: 'Course_Outline_CSC301.pdf',
    type: 'pdf',
    category: 'document',
    size: 2457600, // 2.4 MB
    senderId: 'staff-002',
    senderName: 'Chioma Okafor',
    recipientIds: ['staff-001'],
    uploadedAt: '2025-01-12T10:30:00Z',
    downloadCount: 3,
    isDownloaded: true,
    description: 'Updated course outline for the second semester',
  },
  {
    id: 'file-002',
    name: 'Research_Proposal_Draft.docx',
    type: 'docx',
    category: 'document',
    size: 1843200, // 1.8 MB
    senderId: 'staff-003',
    senderName: 'Emeka Nwankwo',
    recipientIds: ['staff-001', 'staff-002'],
    uploadedAt: '2025-01-11T14:15:00Z',
    downloadCount: 1,
    isDownloaded: false,
    description: 'Please review and provide feedback',
  },
  {
    id: 'file-003',
    name: 'Budget_Report_Q4.xlsx',
    type: 'xlsx',
    category: 'document',
    size: 512000, // 500 KB
    senderId: 'staff-001',
    senderName: 'Adebayo Johnson',
    recipientIds: ['staff-002'],
    uploadedAt: '2025-01-10T09:00:00Z',
    downloadCount: 5,
    isDownloaded: true,
  },
  {
    id: 'file-004',
    name: 'Conference_Presentation.pptx',
    type: 'pptx',
    category: 'document',
    size: 8388608, // 8 MB
    senderId: 'staff-002',
    senderName: 'Chioma Okafor',
    recipientIds: ['staff-001', 'staff-003'],
    uploadedAt: '2025-01-09T16:45:00Z',
    downloadCount: 2,
    isDownloaded: true,
    description: 'Slides for the upcoming academic conference',
  },
  {
    id: 'file-005',
    name: 'Lab_Equipment_Photo.jpg',
    type: 'jpg',
    category: 'image',
    size: 3145728, // 3 MB
    senderId: 'staff-003',
    senderName: 'Emeka Nwankwo',
    recipientIds: ['staff-001'],
    uploadedAt: '2025-01-08T11:20:00Z',
    downloadCount: 0,
    isDownloaded: false,
  },
  {
    id: 'file-006',
    name: 'Lecture_Recording_Week1.mp4',
    type: 'mp4',
    category: 'video',
    size: 52428800, // 50 MB
    senderId: 'staff-001',
    senderName: 'Adebayo Johnson',
    recipientIds: ['staff-002', 'staff-003'],
    uploadedAt: '2025-01-07T13:00:00Z',
    downloadCount: 8,
    isDownloaded: true,
    description: 'Introduction to Data Structures',
  },
  {
    id: 'file-007',
    name: 'Department_Documents.zip',
    type: 'zip',
    category: 'archive',
    size: 15728640, // 15 MB
    senderId: 'staff-002',
    senderName: 'Chioma Okafor',
    recipientIds: ['staff-001'],
    uploadedAt: '2025-01-06T08:30:00Z',
    downloadCount: 1,
    isDownloaded: true,
  },
  {
    id: 'file-008',
    name: 'Podcast_Interview.mp3',
    type: 'mp3',
    category: 'audio',
    size: 10485760, // 10 MB
    senderId: 'staff-003',
    senderName: 'Emeka Nwankwo',
    recipientIds: ['staff-001', 'staff-002'],
    uploadedAt: '2025-01-05T15:45:00Z',
    downloadCount: 4,
    isDownloaded: false,
    description: 'Faculty research discussion podcast',
  },
];

export const mockActivities: FileActivity[] = [
  {
    id: 'act-001',
    fileId: 'file-001',
    fileName: 'Course_Outline_CSC301.pdf',
    action: 'downloaded',
    performedBy: 'Adebayo Johnson',
    performedAt: '2025-01-12T14:30:00Z',
  },
  {
    id: 'act-002',
    fileId: 'file-002',
    fileName: 'Research_Proposal_Draft.docx',
    action: 'shared',
    performedBy: 'Emeka Nwankwo',
    performedAt: '2025-01-11T14:15:00Z',
  },
  {
    id: 'act-003',
    fileId: 'file-003',
    fileName: 'Budget_Report_Q4.xlsx',
    action: 'uploaded',
    performedBy: 'Adebayo Johnson',
    performedAt: '2025-01-10T09:00:00Z',
  },
  {
    id: 'act-004',
    fileId: 'file-004',
    fileName: 'Conference_Presentation.pptx',
    action: 'viewed',
    performedBy: 'Chioma Okafor',
    performedAt: '2025-01-09T17:00:00Z',
  },
  {
    id: 'act-005',
    fileId: 'file-006',
    fileName: 'Lecture_Recording_Week1.mp4',
    action: 'downloaded',
    performedBy: 'Emeka Nwankwo',
    performedAt: '2025-01-08T10:00:00Z',
  },
];
